#!/usr/bin/env bash
# Build the Protection Suite dashboard plugin bundle from src/.
#
# One plugin = ONE nav tab (the manifest's `tab` is a single object — measured in
# hermes_cli/web_server_dashboard.py), so this tree produces one plugin dir:
#
#   ~/.hermes/plugins/protection-suite/
#     plugin.yaml                 general-plugin manifest (the enable gate reads this)
#     __init__.py                 no-op agent-side registration
#     dashboard/manifest.json     tab + entry + css + api
#     dashboard/dist/index.js     the IIFE bundle (core + page + register footer)
#     dashboard/dist/style.css    theme-true CSS (var(--color-*))
#     dashboard/plugin_api.py     FastAPI router, mounted at /api/plugins/protection-suite/
#
# usage: ./build.sh     (idempotent; re-run after editing src/ — then restart the dashboard,
#                        because plugin_api.py routes mount at startup only)
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGINS_DIR="$(dirname "$HERE")"
NAME="protection-suite"
PAGE="suite"
DIR="$PLUGINS_DIR/$NAME"

mkdir -p "$DIR/dashboard/dist"

bundle="$DIR/dashboard/dist/index.js"
{
  printf '/* %s — generated by build.sh from src/; edit src/ and re-run, do not edit this file. */\n' "$NAME"
  printf '(function () {\n  "use strict";\n\n'
  printf '  var SDK = window.__HERMES_PLUGIN_SDK__;\n'
  printf '  if (!SDK || !SDK.React) { console.error("%s: plugin SDK unavailable"); return; }\n' "$NAME"
  printf '  var React = SDK.React;\n'
  printf '  var h = React.createElement;\n'
  printf '  var useState = React.useState, useEffect = React.useEffect, useCallback = React.useCallback;\n'
  printf '  var fetchJSON = SDK.fetchJSON;\n'
  cat "$HERE/src/core.js"
  printf '\n/* ---- page: %s ---- */\n' "$PAGE"
  cat "$HERE/src/pages/$PAGE.js"
  printf '\n  window.__HERMES_PLUGINS__.register("%s", %sPage);\n' "$NAME" "$(echo "$PAGE" | sed 's/^./\U&/')"
  printf '})();\n'
} > "$bundle"

cp "$HERE/src/style.css" "$DIR/dashboard/dist/style.css"
cp "$HERE/templates/manifest.json" "$DIR/dashboard/manifest.json"

echo "built $NAME -> $bundle ($(wc -c < "$bundle") bytes)"
node --check "$bundle" && echo "  syntax ok"
python3 -c "import ast,sys;ast.parse(open('$DIR/dashboard/plugin_api.py').read())" && echo "  plugin_api.py parses"
echo
echo "Next: enable '$NAME' in plugins.enabled for the root config AND every profile (a user-source"
echo "plugin absent from a profile's enabled list makes that profile's app view answer 404), then"
echo "restart the dashboard (plugin_api.py mounts its routes at startup only)."
